# GLOBAL STUFF
model_version: 3.6B
dtype: bfloat16

# LoRA specific
module_filters: [".attn"]
rank: 16
train_tokens: null

effnet_checkpoint_path: /home/kevin/models/stable-cascade/effnet_encoder.safetensors
previewer_checkpoint_path: /home/kevin/models/stable-cascade/previewer.safetensors
generator_checkpoint_path: /home/kevin/models/stable-cascade/stage_c_bf16.safetensors
lora_checkpoint_path: /home/kevin/models/stable-cascade/lora_stage_c_bf16.safetensors
