# GLOBAL STUFF
model_version: 3B
dtype: bfloat16

# For demonstration purposes in reconstruct_images.ipynb
webdataset_path: file:inference/imagenet_1024.tar
batch_size: 4
image_size: 512
grad_accum_steps: 1

effnet_checkpoint_path: /home/kevin/models/stable-cascade/effnet_encoder.safetensors
stage_a_checkpoint_path: /home/kevin/models/stable-cascade/stage_a.safetensors
generator_checkpoint_path: /home/kevin/models/stable-cascade/stage_c_bf16.safetensors
