# GLOBAL STUFF
experiment_id: finetuned_stage_c_bf16
checkpoint_path: /datadrive/models/stable-cascade/finetuned_stage_c_bf16
output_path: /datadrive/models/stable-cascade/finetuned_stage_c_bf16
model_version: 3.6B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 2.0e-5
batch_size: 1
image_size: 1024
grad_accum_steps: 1
updates: 3000
backup_every: 1000
save_every: 250
warmup_updates: 300
use_fsdp: False

# GDF
adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: file:/datadrive/data/lifestyle_dataset_v2.tar
effnet_checkpoint_path: /datadrive/models/stable-cascade/effnet_encoder.safetensors
previewer_checkpoint_path: /datadrive/models/stable-cascade/previewer.safetensors
generator_checkpoint_path: /datadrive/models/stable-cascade/stage_c_bf16.safetensors
